[DSG-101] beschrijving ondersteuning CRSen
Geonovum/disgeo-imsor pull request #76
Opened 2022-04-26 07:53 UTC by pmaria

Nog draft, uitsluitsel over CRS tbv EEZ moet nog verwerkt worden

2022-04-28 08:15 UTC, lvdbrink reviewed
Ziet er al goed uit. Punten:
 - Uitzoekpunt: de EEZ zone is mogelijk niet het enige disgeo object waarvoor geldt dat RD geen optie is. Wellicht ook de andere bestuurlijke gebieden op zee en wellicht windturbines op zee.
 - Het lijkt me goed om ook CRS URIs te noemen naast EPSG codes. URIs staan [hier](https://geonovum.github.io/KP-APIs/API-strategie-extensies/#crs-negotiation) (stukje scrollen nodig)
 - We moeten ook de 3D varianten van toegestane CRS noemen. Deze zijn te vinden in de CRS handreiking of in de link bij het vorige punt.

2022-04-28 10:51 UTC, pmaria commented
Thanks.

> * We moeten ook de 3D varianten van toegestane CRS noemen. Deze zijn te vinden in de CRS handreiking of in de link bij het vorige punt.

In het stuk noem ik nu:

> Bij 3D geometrieen geldt de volgende EPSG code horende bij het CRS:
> * RDNAP - epsg:7415
> * ETRF2000 - epsg:9067

Welke missen we dan nog?

2022-04-28 11:56 UTC, lvdbrink commented
Ik dacht WGS 84 plus hoogte (3D) aan de uitleverkant, maar die heb je ook al zie ik nu, EPSG:4979. 

http://www.opengis.net/def/crs/OGC/0/CRS84h (for coordinates with height) is daar dan weer de projectie van. Deze wordt genoemd in OGC API Features.

2022-05-03 06:35 UTC, lvdbrink requested changes
IMO moeten we CRS84 (WGS 84 long lat) toevoegen. Dit CRS is voorgeschreven door GeoJSON en OGC API Features.

2022-05-03 11:06 UTC, merged